### ISSUE TITLE
Add Color Options

### ISSUE THREAD

**Issue by andrewmunsell** [Urigo/angular-spinkit#10]
It would be great to have the ability to specify a color for the spinner, even if it were a simple subset of colors (e.g. black, white).

**Comment by hopewise** [comment]
Yes, here is how I did it:

    .wave-spinner>div {
                background-color: burlywood;
        }

**Comment by Mahmoudz** [comment]
Here's how to change the colors for each of the spinners:
_(Note I am using version 1.2.5)_
In this file I am setting all the colors to Red (#FF0000)

```css

.sk-rotating-plane {
  background-color: #FF0000;
}

.sk-double-bounce > .sk-child {
  background-color: #FF0000;
}

.sk-wave > .sk-rect {
  background-color: #FF0000;
}

.sk-wandering-cubes > .sk-cube {
  background-color: #FF0000;
}

.sk-spinner {
  background-color: #FF0000;
}

.sk-chasing-dots > .sk-child {
  background-color: #FF0000;
}

.sk-three-bounce > .sk-child {
  background-color: #FF0000;
}

.sk-circle .sk-child:before {
  background-color: #FF0000;
}

.sk-cube-grid > .sk-cube {
  background-color: #FF0000;
}

.sk-fading-circle > .sk-circle:before {
  background-color: #FF0000;
}

.sk-folding-cube > .sk-cube:before {
  background-color: #FF0000;
}
```
